import 'package:audio_service/audio_service.dart';
import 'package:flutter/foundation.dart';

class TtsAudioHandler extends BaseAudioHandler {
  static Future<TtsAudioHandler> init() async {
    return await AudioService.init(
      builder: () => TtsAudioHandler(),
      config: const AudioServiceConfig(
        androidNotificationChannelId: 'com.audire.app.channel.audio',
        androidNotificationChannelName: 'Audire Playback',
        androidNotificationOngoing: true,
        androidShowNotificationBadge: true,
        // FIX: Point to your actual app icon (generated by flutter_launcher_icons)
        androidNotificationIcon: 'mipmap/launcher_icon', 
        // FIX: Allow clicks on the notification to open the app
        androidNotificationClickStartsActivity: true, 
      ),
    );
  }

  void setMediaItem(String title, Duration duration) {
    mediaItem.add(MediaItem(
      id: 'audire_tts',
      album: 'Audire Reader',
      title: title,
      artist: 'Reading Now', // You can change this to "Audire"
      duration: duration,
      // Note: For offline album art, we would need to copy an asset to a local file.
      // For now, this URI is a placeholder. If offline, it shows a default music icon.
      artUri: Uri.parse('https://via.placeholder.com/150/512DA8/FFFFFF?text=Audire'),
    ));
  }

  void setPlaybackState({required bool isPlaying}) {
    playbackState.add(playbackState.value.copyWith(
      controls: [
        // Define controls in order: Rewind, Play/Pause, FastForward, Stop
        MediaControl.rewind,
        if (isPlaying) MediaControl.pause else MediaControl.play,
        MediaControl.fastForward,
        MediaControl.stop,
      ],
      systemActions: const {
        MediaAction.seek,
        MediaAction.seekForward,
        MediaAction.seekBackward,
      },
      // FIX: Ensure the first 3 buttons (Rewind, Play, FF) show in the compact view
      androidCompactActionIndices: const [0, 1, 2], 
      playing: isPlaying,
      processingState: AudioProcessingState.ready,
    ));
  }

  @override
  Future<void> play() async {
    playbackState.add(playbackState.value.copyWith(playing: true));
  }

  @override
  Future<void> pause() async {
    playbackState.add(playbackState.value.copyWith(playing: false));
  }

  @override
  Future<void> stop() async {
    playbackState.add(playbackState.value.copyWith(playing: false));
    super.stop();
  }

  // Handle Notification Button Clicks
  @override
  Future<void> fastForward() async {
    // Broadcast event to UI
    customEvent.add('fastForward');
  }

  @override
  Future<void> rewind() async {
    // Broadcast event to UI
    customEvent.add('rewind');
  }
}